---

- name: Openstack set demo
  tags: openstack_demo
  hosts: localhost
  connection: local
  roles:
    - openstack_set_demo

- name: Demo web server
  tags: demo_web_server
  hosts: demo
  become: yes
  become_method: sudo
  roles:
    - demo_web_server
