---

- name: Install Apache
  yum:
    name: httpd
    state: latest

- name: Start Apache service
  service:
    name: httpd
    enabled: yes
    state: started

- name: Create a web page
  file:
    path: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
    state: touch

- name: Insert a line into the web page
  lineinfile:
    dest: /var/www/html/index.html
    regexp: '^Hello'
    line: 'Hello guys!!!'
  notify: 'Restart apache'

- name: Display instance IP address
  debug:
    msg: "The floating IP address of the instance is - '{{ ansible_ssh_host }}'"
